### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by bauen2000** [dedeweb/netatmo_display#2]
Hey, 

thanks for your nice project!

Actually i have this problem, what am I doing wrong?

pi@raspberry:~/netatmo $ node index.js
2019-02-06 06:23:44 - info: ====================================================                                                                                                                                                             ==
2019-02-06 04:23:44 - info: [api] starting api server on port 8080
2019-02-06 04:23:44 - info: loading bitmaps and fonts
2019-02-06 04:23:48 - info: script launch after 0m4.592s
2019-02-06 04:23:48 - info: ----------------------------------------------------                                                                                                                                                             --
2019-02-06 04:23:48 - debug: [led] red OFF
2019-02-06 04:23:48 - debug: [led] green ON
2019-02-06 04:23:49 - error: unexpected error ( 1 times)
2019-02-06 04:23:49 - error:  TypeError: Cannot read property 'dashboard_data' o                                                                                                                                                             f undefined
    at /home/pi/netatmo/index.js:544:20
    at tryCatcher (/home/pi/netatmo/node_modules/bluebird/js/release/util.js:16:                                                                                                                                                             23)
    at Promise._settlePromiseFromHandler (/home/pi/netatmo/node_modules/bluebird                                                                                                                                                             /js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pi/netatmo/node_modules/bluebird/js/release                                                                                                                                                             /promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/netatmo/node_modules/bluebird/js/releas                                                                                                                                                             e/promise.js:614:10)
    at Promise._settlePromises (/home/pi/netatmo/node_modules/bluebird/js/releas                                                                                                                                                             e/promise.js:693:18)
    at Async._drainQueue (/home/pi/netatmo/node_modules/bluebird/js/release/asyn                                                                                                                                                             c.js:133:16)
    at Async._drainQueues (/home/pi/netatmo/node_modules/bluebird/js/release/asy                                                                                                                                                             nc.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/netatmo/node_modu                                                                                                                                                             les/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

2019-02-06 04:23:49 - info: completed in 0m0.706s
2019-02-06 04:23:49 - warn: next update is not set, forcing it in 11m
2019-02-06 04:23:49 - debug: [led] red OFF
2019-02-06 04:23:49 - debug: [led] green OFF

**Comment by dedeweb** [comment]
Hi,
Actually, this project won't work out-of-the-box.
It's adapted to my installation, you have to change it a bit to match yours... 
You have to modify  index.js file : 
line 529, you have this code : 
```
let capt_ext = _.find(devices.modules, {
	_id: '02:00:00:13:42:00'
});

let capt_chambre = _.find(devices.modules, {
	_id: '03:00:00:03:94:9a'
});

let capt_bureau = _.find(devices.modules, {
	_id: '03:00:00:05:df:d2'
});
```

You have to change it with the mac addresses of your modules.
